# Generated by Django 3.0.7 on 2020-06-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlocation',
            name='location',
        ),
        migrations.AddField(
            model_name='classlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=17.476566, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=78.303019, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classlocation',
            name='radius',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
