# Generated by Django 3.0.7 on 2020-06-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studs', '0002_auto_20200609_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='classlocation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='classlocation',
            name='location',
            field=models.CharField(default=25, max_length=200),
            preserve_default=False,
        ),
    ]
