# Generated by Django 3.0.7 on 2020-06-23 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studs', '0008_auto_20200623_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlocation',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 6, 23, 15, 40, 48, 118842)),
        ),
        migrations.AlterField(
            model_name='classlocation',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 6, 23, 15, 40, 48, 118818)),
        ),
    ]
