# Generated by Django 3.0.7 on 2020-06-23 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studs', '0009_auto_20200623_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlocation',
            name='location',
        ),
        migrations.AddField(
            model_name='classlocation',
            name='latitude',
            field=models.CharField(default='1N', max_length=200),
        ),
        migrations.AddField(
            model_name='classlocation',
            name='longitude',
            field=models.CharField(default='1N', max_length=200),
        ),
        migrations.AlterField(
            model_name='classlocation',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2020, 6, 23, 15, 43, 54, 171257)),
        ),
        migrations.AlterField(
            model_name='classlocation',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 6, 23, 15, 43, 54, 171225)),
        ),
    ]
