# Generated by Django 3.0.7 on 2020-06-22 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studs', '0005_auto_20200622_1925'),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='lectureclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studs.ClassLocation', to_field='NameOfClass'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='courseenrolled',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='courseenrolled',
            field=models.ManyToManyField(to='studs.ClassLocation'),
        ),
    ]
