# Generated by Django 3.0.7 on 2020-06-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20200622_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='roomno',
            field=models.CharField(default='LC1', max_length=100),
        ),
    ]
